# Generated by Django 4.2 on 2023-04-11 13:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('phone', models.CharField(default='04xxxxxxxx', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number incorrect.', regex='^\\+?251?\\d{9}$')])),
                ('phone1', models.CharField(blank=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number incorrect.', regex='^\\+?251?\\d{9}$')])),
                ('phone2', models.CharField(blank=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number incorrect.', regex='^\\+?251?\\d{9}$')])),
                ('phone3', models.CharField(blank=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number incorrect.', regex='^\\+?251?\\d{9}$')])),
                ('phone4', models.CharField(blank=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number incorrect.', regex='^\\+?251?\\d{9}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='WSD.branch')),
                ('position', models.CharField(choices=[('manager', 'Manager'), ('csm', 'Customer Service Manager'), ('om', 'Operation Manager'), ('do', 'Digital Officer'), ('icm', 'Internal Control Manager'), ('bs', 'Business Manager')], default='Manager', max_length=100)),
                ('m_phone', models.CharField(default='04xxxxxxxx', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number incorrect.', regex='^\\+?251?\\d{9}$')])),
                ('m_phone1', models.CharField(blank=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number incorrect.', regex='^\\+?251?\\d{9}$')])),
                ('m_phone2', models.CharField(blank=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number incorrect.', regex='^\\+?251?\\d{9}$')])),
                ('m_phone3', models.CharField(blank=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number incorrect.', regex='^\\+?251?\\d{9}$')])),
            ],
        ),
    ]
